package com.mindmesh.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a node in the mind map graph.
 * Each node corresponds to an idea or concept that can be connected to other nodes.
 * This entity is persisted in Neo4j as a graph node with relationships to other MindNodes.
 *
 * @author Yuri Pedrosa
 */
@Node("MindNode")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class MindNode {

    /**
     * Unique identifier for the node, auto-generated by Neo4j.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The title or main text of the node (idea/concept).
     */
    private String title;

    /**
     * Optional detailed description of the node.
     */
    private String description;

    /**
     * X-coordinate position on the canvas.
     */
    private double x;

    /**
     * Y-coordinate position on the canvas.
     */
    private double y;

    /**
     * Hex color code for visual representation of the node.
     */
    private String color;

    /**
     * The type of the node (e.g., IDEA, TASK, NOTE).
     */
    private NodeType type;

    /**
     * Timestamp when the node was created.
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp when the node was last updated.
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;

    /**
     * List of nodes connected to this node via "CONNECTED_TO" relationships.
     * This represents the outgoing connections in the graph.
     */
    @Relationship(type = "CONNECTED_TO")
    private List<MindNode> connections = new ArrayList<>();
}
